services:
  frontend:
    image: frontend/secrets-share:v1
    build: ./SecretsShareFrontend/
    ports: 
      - "8000:80"

  backend:
    image: backend/secrets-share:v1
    build: ./SecretsShareServer/SecretsShareServer/
    ports: 
      - "8001:80"

  debug-client:
    image: debug-client/client:v1
    build: ./DebugContainer
    # docker exec -it secretssharewebapp-debug-client-1 bash
  