@startuml
|User Interface|
start
:Call $Link;
:Ask for $Guid-Password;
:Hash $Guid-Password;
:Send $Guid-Key from $Link, $Hashed-Guid-Password to Server;
|Server|
if($Guid-Key !meets format)
:return $Error-code;
|User Interface|
:Display Error;
detach
|Server|
endif
if($Hashed-Guid-Password !meets format)
:return $Error-code;
|User Interface|
:Display Error;
detach
|Server|
endif
if(!($Guid-Key entry exists && $Hashed-Guid-Password matches))
note right
dict<$Guid-Key,($Hashed-Input, $Hashed-Guid-Password)>
end note
else
:return $Error-code;
|User Interface|
:Display Error;
detach
|Server|
endif
:create delete timer with 5min for entry;
:return $Hashed-Input;
|User Interface|
:decrypt $Hashed-Input with Guid-Password;
:Display $Input;
stop
@enduml