@startuml
|User Interface|
start
:$Input string;
:Request $Hashkey-Guid from server;
|Server|
:Generate Random $Guid-Password;
:Temporarily Save $Guid-Password;
|User Interface|
:Generate $Hashed-Input with $Guid-Password;
:Send $Hashed-Input to Server;
|Server|
:Generate Random $Guid-Key;
if($Guid-Key already used) then
:Generate new $Guid-Key;
else
:Generate $Guid-Password;
:Hash $Guid-Password
:Save $Guid-Key with $Hashed-Input & $Hashed-Guid-Password;
note right
dict<$Guid-Key,($Hashed-Input, $Hashed-Guid-Password)>
end note
:Generate $Link (host/$Guid-Key);
endif
:return $Link & $Guid-Password;
|User Interface|
:Display $Link and $Guid-Password;
|Server|
floating note right
Saved entries are deleted after 1h
end note
|User Interface|
stop
@enduml